- name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16


- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
  - mkdir -p /home/vagrant/.kube
  - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
  - chown vagrant:vagrant /home/vagrant/.kube/config